POST http://localhost:3000/posts
Content-Type: application/json

{
    "title":"test title 3",
    "content":"test content 3",
    "slug":"test-title-3",
    "status" : "draft",
    "tags" : [1,2],
    "featureImgUrl" : "https://codehubmm.com/images/logo.png",
    "publishOn" : "2026-04-29T14:30:00.000Z",
    "meta" : {
        "readTime" : "3 min read"
    },
    "authorId" : 1
}