POST http://localhost:3000/posts
Content-Type: application/json

{
    "title":"test title 2",
    "content":"test content 2",
    "slug":"test-title-2",
    "status" : "draft",
    "tags" : [{"label":"ai"}, {"label":"test"}],
    "featureImgUrl" : "https://codehubmm.com/images/logo.png",
    "publishOn" : "2026-04-29T14:30:00.000Z",
    "meta" : {
        "readTime" : "2 min read"
    }
}