PATCH http://localhost:3000/posts
Content-Type: application/json

{
    "id" : 5,
    "title":"test title 5",
    "content":"test content 5",
    "slug":"test-title-5",
    "status" : "draft",
    "tags" : [2],
    "featureImgUrl" : "https://codehubmm.com/images/logo.png",
    "publishOn" : "2026-04-29T14:30:00.000Z",
    "meta" : {
        "readTime" : "5 min read"
    },
    "authorId" : 1
}