POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiamFtZXNkb2VAY29kZWh1Ym1tLmNvbSIsImlhdCI6MTc4MDg1MDg3MiwiZXhwIjoxNzgwODU0NDcyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.aUtO-0NA8yagEKm2fjV4ICOFkYFj2XkE2k9mUAEkQ64
{
    "firstName":"James",
    "lastName":"Doe",
    "email":"jamesdoe@codehubmm.com",
    "password":"HelloWorld1@"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json

{
    "users" : [
        {
            "firstName":"Jhon",
            "lastName":"Doe",
            "email":"johndoe@codehub.com",
            "password":"HelloWorld1@"
        },
        {
            "firstName":"Jack",
            "lastName":"Doe",
            "email":"jackdoe@codehub.com",
            "password":"HelloWorld1@"
        }
    ]
}